version: '3.8'

services:
  voiceapp:
    build:
      context: ./backend/voice-app
    ports:
      - "8084:8084"
    environment:
      - api_key=${api_key}

  # verifytoken:
  #   build:
  #     context: ./backend/auth
  #   ports:
  #     - "8085:8085"

  nginx:
    build:
      context: ./frontend
    ports:
      - "8081:8080"
    depends_on:
      - voiceapp


