[req]
days                           = 365
serial                         = 1
prompt                         = no
default_bits                   = 2048
default_md                     = sha256
distinguished_name             = subject

[subject]
countryName                    = US
stateOrProvinceName            = UT
localityName                   = Salt Lake City
organizationName               = ErikCo
commonName                     = localhost
emailAddress                   = root@localhost